source "http://rubygems.org"
gem "sinatra"
gem "mongo_mapper"
gem "mongomapper_ext"
gem "bson_ext", :platforms => [:mri_18, :mri_19]
gem "rake"
gem "rack"
gem "haml"
gem "tux", :platforms => [:mri_18, :mri_19]
gem "sinatra-reloader"
gem "sinatra-flash"
gem "rdiscount"
gem 'pry', :group => :development
gem 'rspec', :group => :development
